### ISSUE TITLE
Demo failure missing pureconfig dependency

### ISSUE THREAD

**Issue by psg2** [databrickslabs/delta-oms#18]
While trying to run the demo notebooks, the 01.OMS_ProcessFlow notebook fails at cell 10 with a class not found for pureconfig.Deviation. Looking at the Databricks Runtime release notes, this dependency is not included by default and then looking at the build.sbt I see that it is marked as a provided, should this be changed?

https://github.com/databrickslabs/delta-oms/blob/508c65ce6dc422bfc50f17829f34e7cb2f536ea3/build.sbt#L89

**Comment by himanishk** [comment]
@psg2 , DeltaOMS v0.2.0 has a dependency on `pureconfig`. The `pureconfig` jars has to be installed as a separate library on the Databricks cluster.

We would recommend upgrading to DeltaOMS v0.3.0 which does not have dependency on `pureconfig`. That version of DeltaOMS is configured either through command line arguments or spark configurations. Please refer to the [documentation](https://databrickslabs.github.io/delta-oms/) for details. Hope this helps.

**Comment by psg2** [comment]
> @psg2 , DeltaOMS v0.2.0 has a dependency on pureconfig. The pureconfig jars has to be installed as a separate library on the Databricks cluster.

Understood, I did that as well and then run into another issue that I haven't reported.

Will give it a try again on version 0.3.0 to see if it works.

**Comment by himanishk** [comment]
@psg2 , Yes, please try 0.3.0 and let us know if you run into any further issue. Closing this one.
